// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef AUDIOMANAGER_GLOBAL_H
#define AUDIOMANAGER_GLOBAL_H

#define DTK_NAMESPACE Dtk
#define AUDIOMANAGER_NAMESPACE AudioManager
#define DTK_AUDIOMANAGER_NAMESPACE DTK_NAMESPACE::AUDIOMANAGER_NAMESPACE

#define AUDIOMANAGER_USE_NAMESPACE using namespace DTK_AUDIOMANAGER_NAMESPACE;

#define AUDIOMANAGER_BEGIN_NAMESPACE namespace DTK_NAMESPACE { namespace AUDIOMANAGER_NAMESPACE {
#define AUDIOMANAGER_END_NAMESPACE }}

#include <QObject>

#if defined(DTK_STATIC_LIB)
#  define LIBAUDIOMANAGERSHARED_EXPORT
#else
#if defined(LIBAUDIOMANAGER_LIBRARY)
#  define LIBAUDIOMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBAUDIOMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif
